name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r explainers_requirements.txt
        pip install -r https://raw.githubusercontent.com/oxid15/cascade/main/utils_requirements.txt
        pip install .
    - name: Evaluate
      run: |
        cd xaib/evaluation/feature_importance/
        ./evaluate.sh
        cd ../example_selection
        ./evaluate.sh
